core/cart/urls.py
from django.urls import path,re_path
from . import views 

app_name = 'cart'

urlpatterns = [
    
    path('session/add-product/',views.SessionAddProductView.as_view(),name='session-add-product'),
    path('session/update-product-quantity/',views.SessionUpdateProductQuantityView.as_view(),
         name='session-update-product-quantity'),
    path('session/remove-product/',views.SessionRemoveProductView.as_view(),
         name='session-remove-product'),
    path('summary/',views.SessionCartSummaryView.as_view(),name='session-cart-summary')

    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('accounts/',include('accounts.urls')),
    path('shop/',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('order/',include('order.urls')),
    path('payment/',include('payment.urls')),
    path('review/',include('review.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path,re_path
from . import views 

app_name = 'shop'

urlpatterns = [
    
    path('product/list/',views.ShopProductListView.as_view(),name='product-list'),
    re_path(r"product/(?P<slug>[-\w]+)/detail/",views.ShopProductDetailView.as_view(),name="product-detail"),
    path('add-or-remove-wishlist/',views.AddOrRemoveWishlistView.as_view(),name='add-or-remove-wishlist')
    
]

core/templates/includes/latest-products.html
{% load static %}

<!-- Card Grid -->
<div class="container content-space-2 content-space-lg-3">
    <!-- Title -->
    <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
      <h2> جدیدترین محصولات</h2>
    </div>
    <!-- End Title -->

    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mb-3">
        {% for latest_product in latest_products %}
            <div class="col mb-4">
              <!-- Card -->
              <div class="card card-bordered shadow-none text-center h-100">
                <div class="card-pinned">
                  <img class="card-img-top" src="{{latest_product.image.url}}" alt="Image Description">

                  <div class="card-pinned-top-start">
                    <span class="badge bg-success rounded-pill">جدید</span>
                  </div>

                  <div class="card-pinned-top-end">
                    {% if request.user.is_authenticated %}
                    <button type="button" 
                    class="btn btn-outline-secondary btn-xs btn-icon rounded-circle {%if latest_product.id in wishlist_items%} active {%endif%}" 
                    data-bs-toggle="tooltip" 
                    data-bs-placement="top" 
                    title="{%if latest_product.id in wishlist_items%}حذف از علایق{%else%}افزودن به علایق{%endif%}" 
                    onclick="addToWishlist(this, '{{latest_product.id}}')">
                    <i class="bi-heart"></i>
                    </button>
                    {%endif%}
                  </div>
                </div>

                <div class="card-body">
                  <div class="mb-2">
                    {% for category in latest_product.category.all %}
                    <a class="link-sm link-secondary" href="#">{{category.title}}</a>
                    {% if not forloop.last %}
                    ,
                    {% endif %}
                    {% endfor %}
                  </div>

                  <h4 class="card-title">
                    <a class="text-dark" href="{% url 'shop:product-detail' slug=latest_product.slug %}">{{latest_product.title}}</a>
                  </h4>
                  {% if latest_product.is_discounted %}
                    <p class="card-text text-dark fs-4">
                        <span class="formatted-price">{{latest_product.get_show_price}} تومان</span>
                        <span
                            class="text-body me-1 fs-6 formatted-price text-decoration-line-through">{{latest_product.get_show_raw_price}}تومان</span>
                    </p>
                    {% else %}
                    <p class="card-text text-dark fs-4 formatted-price">{{latest_product.get_show_price}} تومان</p>
                    {% endif %}
                </div>

                <div class="card-footer pt-0">
                  <!-- Rating -->
                  <a class="d-inline-flex align-items-center mb-3" href="#">
                    <div class="d-flex gap-1 ms-2">
                        {% for i in "12345" %}
                        {% if i|add:0 <= latest_product.avg_rate %} <span><i
                                class="bi bi-star-fill star-rate"></i></span>
                            {% else %}
                            <span><i class="bi bi-star star-rate"></i></span>
                            {% endif %}

                            {% endfor %}
                            <span class="ms-1">{{latest_product.avg_rate}}/5</span>
                    </div>

                </a>
                <!-- End Rating -->

                  <button type="button" class="btn btn-outline-primary btn-sm btn-transition rounded-pill">افزودن به سبد خرید</button>
                </div>
              </div>
              <!-- End Card -->
            </div>
            {% empty %}
            <div class="row text-center w-100 py-5">
              <p class="text-center">هیچ کالایی برای نمایش وجود ندارد</p>
            </div>
            <!-- End Col -->
            {% endfor %}

    </div>
    <!-- End Row -->

    <div class="text-center">
      <a class="btn btn-outline-primary btn-transition rounded-pill" href="{% url 'shop:product-list' %}">مشاهده تمامی محصولات</a>
    </div>
  </div>
  <!-- End Card Grid -->

core/templates/includes/similar-products.html
    {% load static %}
    <!-- Card Grid -->
    <div class="container content-space-2 content-space-lg-3">
        <!-- Title -->
        <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
          <h2>فقط برای شما</h2>
        </div>
        <!-- End Title -->
  
        <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for similar_product in similar_products %}
            <div class="col mb-4">
              <!-- Card -->
              <div class="card card-bordered shadow-none text-center h-100">
                <div class="card-pinned">
                  <img class="card-img-top" src="{{similar_product.image.url}}" alt="Image Description">

                  <div class="card-pinned-top-start">
                    <span class="badge bg-success rounded-pill">جدید</span>
                  </div>

                  <div class="card-pinned-top-end">
                    {% if request.user.is_authenticated %}
                    <button type="button" 
                    class="btn btn-outline-secondary btn-xs btn-icon rounded-circle {%if similar_product.id in wishlist_items%} active {%endif%}" 
                    data-bs-toggle="tooltip" 
                    data-bs-placement="top" 
                    title="{%if similar_product.id in wishlist_items%}حذف از علایق{%else%}افزودن به علایق{%endif%}" 
                    onclick="addToWishlist(this, '{{similar_product.id}}')">
                    <i class="bi-heart"></i>
                    </button>
                    {%endif%}
                  </div>
                </div>

                <div class="card-body">
                  <div class="mb-2">
                    {% for category in similar_product.category.all %}
                    <a class="link-sm link-secondary" href="#">{{category.title}}</a>
                    {% if not forloop.last %}
                    ,
                    {% endif %}
                    {% endfor %}
                  </div>

                  <h4 class="card-title">
                    <a class="text-dark" href="{% url 'shop:product-detail' slug=similar_product.slug %}">{{similar_product.title}}</a>
                  </h4>
                  {% if similar_product.is_discounted %}
                    <p class="card-text text-dark fs-4">
                        <span class="formatted-price">{{similar_product.get_show_price}} تومان</span>
                        <span
                            class="text-body me-1 fs-6 formatted-price text-decoration-line-through">{{similar_product.get_show_raw_price}}تومان</span>
                    </p>
                    {% else %}
                    <p class="card-text text-dark fs-4 formatted-price">{{similar_product.get_show_price}} تومان</p>
                    {% endif %}
                </div>

                <div class="card-footer pt-0">
                  <!-- Rating -->
                  <a class="d-inline-flex align-items-center mb-3" href="#">
                    {% for i in "12345" %}
                    {% if i|add:0 <= similar_product.avg_rate %} <span><i
                            class="bi bi-star-fill star-rate"></i></span>
                        {% else %}
                        <span><i class="bi bi-star star-rate"></i></span>
                        {% endif %}

                        {% endfor %}
                        <span class="ms-1">{{similar_product.avg_rate}}/5</span>
                  </a>
                  <!-- End Rating -->

                  <button type="button" class="btn btn-outline-primary btn-sm btn-transition rounded-pill">افزودن به سبد خرید</button>
                </div>
              </div>
              <!-- End Card -->
            </div>
            {% empty %}
            <div class="row text-center w-100 py-5">
              <p class="text-center">هیچ کالایی برای نمایش وجود ندارد</p>
            </div>
            <!-- End Col -->
            {% endfor %}

        </div>
        <!-- End Row -->
      </div>
      <!-- End Card Grid -->